### ISSUE TITLE
Linux aarch64 build not working

### ISSUE THREAD

**Issue by 00svd00** [zb3/freej2me#5]
NativeLoader: extracting native libraries to /tmp/freej2me-2199509124339
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: Can't load library: /tmp/freej2me-2199509124339/libmicro3d.so
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1823)
        at java.lang.Runtime.load0(Runtime.java:782)
        at java.lang.System.load(System.java:1098)
        at pl.zb3.freej2me.NativeLoader.loadLibrary(NativeLoader.java:85)
        at ru.woesss.j2me.micro3d.ClassWithNatives.<clinit>(ClassWithNatives.java:7)
        at com.mascotcapsule.micro3d.v3.Texture.<init>(Texture.java:30)
        at ax.<init>(Unknown Source)
        at cc.a(Unknown Source)
        at cd.a(Unknown Source)
        at cy.a(Unknown Source)
        at bk.a(Unknown Source)
        at bg.a(Unknown Source)
        at bq.b(Unknown Source)
        at dd.c(Unknown Source)
        at DeepMIDlet.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:750)

After renaming freej2me-linux-arm64.jar/natives/linux-arm64 to linux-aarch64 everything works normally

**Comment by zb3** [comment]
Apologies for not responding earlier, but github didn't send me any notifications.. :(

Could you check the JAR below? If that works, I'll update the release.

[freej2me-linux-arm64.zip](https://github.com/user-attachments/files/15525690/freej2me-linux-arm64.zip)

**Comment by 00svd00** [comment]
> Apologies for not responding earlier, but github didn't send me any notifications.. :(
> 
> Could you check the JAR below? If that works, I'll update the release.
> 
> [freej2me-linux-arm64.zip](https://github.com/user-attachments/files/15525690/freej2me-linux-arm64.zip)
Yes, this version works without any modifications.
